import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SideBar from "@/components/SideBar";
import Navbar from "@/components/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css"
          rel="stylesheet"
        />
      </Head>

      <body className={inter.className}>
        <div className="flex text-black">
          <div className="flex-1 shadow-lg">
            <SideBar />
          </div>
          <div className="flex-5">
            <div className="relative bg-gray-200">
              <Navbar />
              {/* Header */}
              <Header />
              <div className=" px-14 mx-auto w-full -mt-24 min-h-[55vh]">
                {children}
              </div>
              <Footer />
            </div>
          </div>
        </div>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"
          async
        />
      </body>
    </html>
  );
}
